name: default
concurrency:
  group: ${{ github.event.label == null && github.head_ref || github.run_id }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - release-*
    types:
      - opened
      - synchronize
      - reopened
      - labeled
jobs:
  default:
    if: (!startsWith(github.head_ref, 'renovate/') && !startsWith(github.head_ref, 'dependabot/')) && (github.event.label == null || (contains(fromJSON('["integration/reproducibility"]'), github.event.label.name)))
    permissions:
      packages: write
    runs-on:
      - self-hosted
      - pkgs
    services:
      buildkitd:
        image: moby/buildkit:buildx-stable-1
        ports:
          - 1234:1234
        options: --privileged
        volumes:
          - /var/lib/buildkit/${{ github.repository }}:/var/lib/buildkit
          - /usr/etc/buildkit/buildkitd.toml:/etc/buildkit/buildkitd.toml
    steps:
      - name: checkout
        uses: actions/checkout@v3
