name: default
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
      - release-*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - release-*
jobs:
  default:
    if: (!startsWith(github.head_ref, 'renovate/') && !startsWith(github.head_ref, 'dependabot/'))
    permissions:
      packages: write
    runs-on:
      - self-hosted
      - pkgs
    outputs:
      labels: ${{ steps.workflow-run-info.outputs.pullRequestLabels }}
    services:
      buildkitd:
        image: moby/buildkit:buildx-stable-1
        ports:
          - 1234:1234
        options: --privileged
        volumes:
          - /var/lib/buildkit/${{ github.repository }}:/var/lib/buildkit
          - /usr/etc/buildkit/buildkitd.toml:/etc/buildkit/buildkitd.toml
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Unshallow
        run: |
          git fetch --prune --unshallow
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: remote
          endpoint: tcp://localhost:1234
          append: |
            - endpoint: tcp://buildkit-arm64.ci.svc.cluster.local:1234
              platforms: linux/arm64
      - name: build
        run: |
          make
      - name: Login to registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
      - name: Push to registry
        if: github.event_name != 'pull_request'
        run: |
          make PUSH=true
      - name: Retrieve workflow info
        id: workflow-run-info
        uses: potiuk/get-workflow-origin@v1_5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  reproducibility:
    runs-on:
      - self-hosted
      - pkgs
    if: contains(needs.default.outputs.labels, 'integration/reproducibility')
    needs:
      - default
    services:
      buildkitd:
        image: moby/buildkit:buildx-stable-1
        ports:
          - 1234:1234
        options: --privileged
        volumes:
          - /var/lib/buildkit/${{ github.repository }}:/var/lib/buildkit
          - /usr/etc/buildkit/buildkitd.toml:/etc/buildkit/buildkitd.toml
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Unshallow
        run: |
          git fetch --prune --unshallow
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: remote
          endpoint: tcp://localhost:1234
          append: |
            - endpoint: tcp://buildkit-arm64.ci.svc.cluster.local:1234
              platforms: linux/arm64
      - name: reproducibility
        run: |
          make reproducibility-test
